### ISSUE TITLE
Which is the best way to add current request object for some templates?

### ISSUE THREAD

**Issue by MarSoft** [klen/muffin-jinja2#1]
I need to display current user information in header on nearly every page (as all pages use `base.html` template). And I don't want to add `app.ps.jinja2.render(..., user=request.user)`. Which is the best way to pass that object into templates globally?
I tried to use context processors, but they have no access to current request object.
Users are managed with `muffin_session` plugin.

**Comment by klen** [comment]
For now there is no an easy way to do it. Only by ``app.ps.jinja2.render(..., request=request)``. I can do some tricks with "magic" ``muffin.slocal`` object, but don't like the way.

**Comment by MarSoft** [comment]
Just for record, here is the workaround I came up with:
In helpers.py:

    async def render(req, TPL, **kwargs):
        kwargs['request'] = req
        kwargs['user'] = await app.ps.session.load_user()
        # ...
        return await app.ps.jinja2.render(tpl, **kwargs)

And in my routes:

    @app.register('/')
    async def index(req):
        # ...
        return await render(req, 'index.html', a=b...)
